esphome:
  name: pogoda-esp32
  friendly_name: POGODA-ESP32

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "YbTXq0ScxXtfKcooXYXy7SNcJlfL0Sqny+qpD6RFH2U="

ota:
  - platform: esphome
    password: "[MASKOWANE_HASLO]"

wifi:
  ssid: "[MASKOWANE_WIFI]"
  password: "[MASKOWANE_HASLO]"
  manual_ip:
    static_ip: [MASKOWANE_IP]
    gateway: [MASKOWANE_IP]
    subnet: [MASKOWANE_IP]
    dns1: [MASKOWANE_IP]
  ap:
    ssid: "[MASKOWANE_WIFI]"
    password: "[MASKOWANE_HASLO]"

captive_portal:

i2c:
  sda: GPIO16
  scl: GPIO14
  scan: true

sensor:
  - platform: bme280_i2c
    address: 0x76
    temperature:
      name: "Temperatura zewnętrzna"
    humidity:
      name: "Wilgotność zewnętrzna"
    pressure:
      name: "Ciśnienie"
    update_interval: 30s